---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(readxl)
library(lme4)
```


```{r}
data <- read_excel('data/StockX-Data-Contest-2019-3.xlsx', sheet = 2)

# Renaming columns
names(data) <- make.names(names(data), unique = TRUE)

# categoricals
data$Sneaker.Name <- as.factor(data$Sneaker.Name)
data$Buyer.Region <- as.factor(data$Buyer.Region)

# new column
data$Sneaker.General.Type <- ifelse(grepl("Yeezy-Boost-350", data$Sneaker.Name), "Adidas Yeezy", 
                            ifelse(grepl("Off-White",  data$Sneaker.Name), "Nike Off White","no"))

data$Sneaker.Specific.Type <- ifelse(grepl("Yeezy-Boost-350", data$Sneaker.Name), "Yeezy", 
                                     ifelse(grepl("Air-Max-90",  data$Sneaker.Name), "Air Max 90",
                                            ifelse(grepl("VaporMax", data$Sneaker.Name), "VaporMax",
                                                   ifelse(grepl("Air-Presto", data$Sneaker.Name), "Air Presto",
                                                          ifelse(grepl("Air-Jordan-1", data$Sneaker.Name), "Air Jordan 1",
                                                                 ifelse(grepl("Blazer", data$Sneaker.Name), "Blazer",
                                                                        ifelse(grepl("Air-Force", data$Sneaker.Name),"Air Force 1",
                                                                               ifelse(grepl("Air-Max-97", data$Sneaker.Name),"Air Max 97",
                                                                                      ifelse(grepl("Hyperdunk", data$Sneaker.Name),"Hyperdunk 2017",
                                                                                             ifelse(grepl("Zoom-Fly", data$Sneaker.Name),"Zoom Fly","no"))))))))))
data$Order.Year.Month <- format(as.Date(data$Order.Date), "%Y-%m")

data

# write.csv(data, "data/cleaned_stockX_data.csv", row.names = FALSE)

```
```{r}
data <- read_csv("data/processed/cleaned_stockX_data.csv")

data
```

```{r}
fake_list = c('Yeezy', 'Zoom Fly')

p <- ggplot(data %>% filter(Sneaker.Specific.Type %in% fake_list), aes(y = Sale.Price, x = Order.Year.Month, color = Sneaker.Specific.Type, group = Sneaker.Specific.Type)) + 
  geom_line(stat = 'summary', fun = mean) + 
  labs(x = "Time", y = "Sale Price", title = "Sale Price vs Time") + 
  theme(axis.text.x = element_text(angle = 90))

p
```

```{r}
sneaker_size = c('14.0')

ggplot(data %>% filter(Sneaker.Specific.Type %in% fake_list &
                         Shoe.Size %in% sneaker_size), aes(x = Sale.Price, y = Sneaker.Specific.Type)) + 
  geom_violin() + 
  geom_point(stat = 'summary', fun = 'mean', color = 'red', alpha = 0.3) +
  ggtitle("Sale Price")

```

```{r}
ggplot(data, aes(y = Shoe.Size)) + geom_bar() 
```

```{r}
data %>% group_by(Shoe.Size) %>% summarize(price = mean(Sale.Price))

```

